<?php if ($this->toolIsAccessible): ?>	
	<!-- Single Tab Start-->
	<div class="row row-merge">
		<div class="col-sm-12 bg-white">
			<div class="innerAll">
				<div class="tab-content">								
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce elementum consequat auctor. Nunc eget quam ligula. Phasellus dictum urna id iaculis eleifend. Ut ut augue hendrerit lacus volutpat mollis a vitae massa. Etiam ex arcu, finibus eget velit et, semper pharetra neque. Proin a pellentesque arcu. In gravida sagittis diam, at consectetur turpis volutpat vel. Integer suscipit ipsum vitae consequat tristique. Fusce semper lectus mattis metus pellentesque, ac tincidunt ipsum dignissim.</p>	
				</div>
			</div>
		</div>
	</div>
	<!-- Single Tab End-->
<?php else: ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php endif; ?>