<?php if ($this->toolIsAccessible): ?>
	<div class="widget widget-tabs widget-tabs-responsive">
	    <!-- Tabs Heading Start-->
	    <div class="widget-head">
	        <ul class="nav nav-tabs">
	        	#TABHEADER  
	        </ul>
	    </div>
	    <!-- Tabs Heading End -->
	</div>

	<div class="clear">
	</div>
	
	<!-- Tabs Content Start-->
	<div class="row row-merge">
		<div class="col-sm-12 bg-white">
			<div class="innerAll">
				<div class="tab-content">
					#TABCONTENT			
				</div>
			</div>
		</div>
	</div>
	<!-- Tabs Content End-->

<?php else: ?>
    <div class="no-rights-container">
        <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_rights'); ?></span>
    </div>
<?php endif; ?>