<div id="<?php echo $this->id; ?>" class="steps-content">
    <h3><?php echo $this->translate('tr_melisdashboardplugincreator_title_step_'.$curStep) ?></h3>
    <p><?php echo $this->translate('tr_melisdashboardplugincreator_desc_step_'.$curStep) ?></p>
    
    <?php 
        if($curStep != 4){ ?>
            <div class="row">  
                 <?php                   
                    echo $this->partial('melis-dashboard-plugin-creator/partial/render-step'.$curStep, array(
                        'stepForm' => $this->stepForm,
                        'data' => $this->data                            
                     ));                      
                 ?>                 
            </div>  
    <?php    }else{ ?>
                <?php echo $this->partial('melis-dashboard-plugin-creator/partial/render-step'.$curStep, array(
                    'stepForm' => $this->stepForm,
                    'data' => $this->data,                   
                 ));   
           }
    ?>      
    
    <div class='d-flex justify-content-between'>
        <div style="text-align: left;">
            <?php 
                if($curStep != 1){ ?>
                        <button class="btn btn-default btn-steps" data-curstep="<?=$this->curStep?>" data-nextstep="<?=$this->curStep-1?>"><?php echo $this->translate('tr_melisdashboardplugincreator_back') ?></button>
            <?php    }
            ?>
        </div>
       
       <?php 
        if($this->curStep == 5){ ?>

            <div style="text-align: right;">
                <button class="btn btn-default btn-steps dpc-validate" data-curstep="<?=$this->curStep?>" data-nextstep="<?=$this->curStep?>" data-validate="true"><?php echo $this->translate('tr_melisdashboardplugincreator_finish_and_create_the_plugin') ?></button>
            </div>
            
        <?php }else{ ?>
           
            <div style="text-align: right;">
                <button class="btn btn-default btn-steps dpc-validate" data-curstep="<?=$this->curStep?>" data-nextstep="<?=$this->nextStep?>" data-validate="true"><?php echo $this->translate('tr_melisdashboardplugincreator_next') ?></button>
            </div>
       <?php }
       ?>        
    </div>
</div>
