<?php
    $id = $this->zoneconfig['conf']['id'];
    $melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<div class="innerAll spacing-x2 melis-dashboard-plugin-creator" id="<?php echo $id ?>" data-melisKey="<?php echo $melisKey; ?>">
    <div class="innerAll spacing-x2">
       <!-- Tool Content-->
       <?php if (empty($this->fPErr)) { ?>
            <div class="wizard wizard-design">
                <!-- Wizard heading -->
                <div class="wizard-head melis-dashboard-plugin-creator-steps">
                    <ul class="bwizard-steps">
                        <?php
                            if (!empty($this->toolSteps)) {
                                $ctr = 0;
                                foreach ($this->toolSteps as $key => $config) {
                                    $clss = !$ctr++ ? 'class="active"' : '';
                                    echo '<li '.$clss.' id="dpc_'.$key.'"><span><i class="fa '.$config['icon'].' fa-lg" aria-hidden="true"></i> '.$this->translate($config['name']).'</span></li>';
                                }
                            }
                        ?>
                    </ul>
                </div>
                <!-- // Wizard heading END -->
                <div class="widget">
                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <?php
                                    echo $this->melisdashboardplugincreator_steps;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="alert alert-warning">
                <h3><?php echo $this->translate('tr_melisdashboardplugincreator_fp_title') ?></h3>
                <p><?php echo $this->translate('tr_melisdashboardplugincreator_fp_msg') ?></p>
                <br>
                <?php foreach ($this->fPErr as $err) { ?>
                    <p style="display: list-item;list-style-type: disc;list-style-position: inside;"><?php echo $this->translate($err) ?></p>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>