<div id="<?php echo $this->id; ?>" class="steps-content">           
    <div class="row">
        <div class="col-md-12">  
            <div class = 'alert alert-default' role = 'alert'>                         
                <i class="fa fa-thumbs-o-up fa-5x fa-fw pull-left text-primary-custom"></i>
                <p><strong><?php echo $this->translate('tr_melisdashboardplugincreator_finalization_success_title') ?></strong></p>
              
                <?php if ($this->restartRequired) { ?>
                    <p id="tc-restart-msg"><?php echo $this->translate('tr_melisdashboardplugincreator_finalization_success_desc_with_counter') ?></p>
                <?php } else { ?>
                    <p><?php echo $this->translate('tr_melisdashboardplugincreator_finalization_success_desc') ?></p>
                <?php } ?>   
            </div>            
         </div>
    </div>        
</div>

<script>
    <?php if ($this->restartRequired){ ?>

        var countdown = function(){
            var tcResCd = parseInt($("#tc-restart-cd").text());
            var countDown = setInterval(function() {
                if (tcResCd < 1){
                    $("#tc-restart-msg").text("<?php echo $this->translate('tr_melisdashboardplugincreator_refreshing') ?>");
                    clearInterval(countDown);
                    window.location.reload();                    
                } else {
                    $("#tc-restart-cd").text(tcResCd);
                    tcResCd--;
                }
            }, 1000);
        };
    <?php } 

    if ($this->restartRequired) { ?>
        countdown();
    <?php } ?>
</script>







   