<div class="col-xs-12 col-md-3">
    <div class="product-text-tab-container">
        <ul class="nav-tabs product-text-tab">    
            <?php                 
                $ctr = 0;
                foreach ($this->data['languages'] As $key => $val) { ?>
                <li class="<?php echo ($ctr++) ?: 'active'?>">
                    <a class="clearfix" data-toggle="tab" href="#dpccreator-text-transaltions-<?php echo $val['lang_locale']?>" aria-expanded="false">
                        <?php echo $val['lang_label']?>
                    </a>
                </li>
            <?php } ?>
                
        </ul>
    </div>
</div>
<div class="col-xs-12 col-md-9">
    <div class="tab-content">      
        <?php $ctr = 0; foreach ($this->stepForm['languageForm'] As $key => $form):?>
            <div id="dpccreator-text-transaltions-<?php echo $key ?>" class="tab-pane <?php echo ($ctr++) ? '': 'active'?>">
                <?php                  
                    $form->prepare();
                    $form->setAttribute('id', $form->getAttribute('id').'-'.$key);
                    $form->setAttribute('id', $key.'-'.$form->getAttribute('id'));

                    echo $this->form()->openTag($form);
                    echo $this->melisFieldCollection($form);
                    echo $this->form()->closeTag();
                ?>
            </div>
        <?php endforeach;?>
    </div>
</div>

<div class="col-xs-12 col-md-12" id = 'pluginThumbnailUploadArea'>
    <?php
        $form = $this->stepForm['form2'];
        echo $this->form()->openTag($form);
        echo $this->melisFieldCollection($form);
        echo $this->form()->closeTag();

        if(!empty($this->data['thumbnail'])){
            $explodePath = explode('/',$this->data['thumbnail']);
            $fileName = $explodePath[count($explodePath)-1];

            $form->get('dpc_plugin_upload_thumbnail')->setValue($fileName);
        }
    ?>

    <div class="progressContent hidden">
        <?= $this->translate('tr_melisdashboardplugincreator_input_file_uploading'); ?>
        <div class="progress">
            <span class="status float-right text-danger hidden">0%</span>
            <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow=0 aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            </div>
        </div><br/>
    </div>                  
    <?php 
        if(!empty($this->data['thumbnail'])){ ?>
            <div class="col-xs-12 col-lg-6">
                <div class="plugin_thumbnail_div" >
                    <img src="<?= $this->data['thumbnail']?>" class = "plugin_thumbnail">  
                    <div class="hover-details">
                        <div class="me-p-btn-cont">
                            <a class="" href="<?= $this->data['thumbnail']?>" target="_blank">
                                <i class="fa fa-eye"></i>
                            </a>       
                            <a id="removePluginThumbnail" data-type="image">
                                <i class="fa fa-times"></i>
                            </a>                                                                              
                        </div>
                    </div>
                 </div>
            </div>           
    <?php    }
    ?>      
</div>






   